### ISSUE TITLE
Master does not build on GOOS=darwin

### ISSUE THREAD

**Issue by ewoutp** [vishvananda/netlink#135]
```
$ go get github.com/vishvananda/netlink
# github.com/vishvananda/netlink
../../go/src/github.com/vishvananda/netlink/filter.go:225: undefined: nl.TcPolice
```

PS. This issue was found with the use of this library in coreos/fleet.
See https://github.com/coreos/fleet/pull/1604

**Comment by vishvananda** [comment]
@ewoutp I believe the library will build properly with the branch at fix-darwin. Can you try out a fleet build using that branch? Once you verify that it builds I will merge it. I might suggest also suggest that you also modify your cod to only include the netlink package for linux builds since I don't think it will actually do anything useful on Darwin.

**Comment by ewoutp** [comment]
With this branch it builds fine 👍 

I'm not a maintainer of fleet, but I'll relay your message
