### ISSUE TITLE
netlink.LinkSetNsFd(link Link, fd int),can fd be a string

### ISSUE THREAD

**Issue by davidstack** [vishvananda/netlink#161]
in the linux command. we can set netlink to ns like this:
  ip link set veth-b netns 77382ee10e60

can this function netlink.LinkSetNsFd(link Link, fd int) ,support string as the fd parment? thanks

**Comment by vishvananda** [comment]
No you cannot pass a string directly. However iproute2 stores its "named" network namespaces as files in /var/run/netns/ so you could do something like the following:
```
  fd, err := syscall.Open("/var/run/netns/ 77382ee10e60", syscall.O_RDONLY, 0)
  if err != nil {
    return err
  }
  if err := netlink.LinkSetNsFd(link, fd); err != nil {
    return err
  }
  if err := syscall.Close(fd); err != nil {
    return err
  }
```

Note that instead of directly using the Open and Close syscalls, you can also open the file with os.Open and convert it to an int fd using [Fd()](https://golang.org/pkg/os/#File.Fd) on the resulting file.

**Comment by davidstack** [comment]
@vishvananda  thank you very much. i found another method
` import github.com/vishvananda/netns
  nshandler, nsError := netns.GetFromPath("/var/run/netns/77382ee10e60")
  if nsError != nil {
	  fmt.Println("get ns handler failed", nsError)
         return nil, nsError
	}
	return int(nshandler)),nil`
i will test this method and you suggestion.thanks
