### ISSUE TITLE
TxQLen is zero by default

### ISSUE THREAD

**Issue by LK4D4** [vishvananda/netlink#26]
But actually seems like it should be 1000. I'm not sure how I can fix this, should I implement `SetTxQLen` and move it out of `Attrs`?
@vishvananda WDYT?

**Comment by vishvananda** [comment]
@LK4D4 sorry i missed this one. You mean when creating a new link it should default to 1000? I don't see anywhere in iproute2 where it sets it to 1000. But maybe it leaves it empty and the kernel defaults it to 1000?

**Comment by vishvananda** [comment]
it looks like both txqueuelen and mtu should default to -1 and are only sent if they are set. This means changing TxQLen to an int and and switching the mtu setting to activate if it is not -1 instead of zero. LinkAttrs probably needs to grow a constructor to make sure the -1s get set properly. The alternative would be to change these values into pointers, but that seems like a more severe break for users
