### ISSUE TITLE
CI seems broken

### ISSUE THREAD

**Issue by tfukushima** [vishvananda/netlink#262]
I created the PR #261 and in the first patch of two I switched the version of Go to 1.9. Then CI didn't accept that since several tests failed with "Failed to add qdisc" and "Failed to remove qdisc" errors as follow.

https://travis-ci.org/vishvananda/netlink/builds/269067407?utm_source=github_status&utm_medium=notification

I wondered if the version difference really mattered and took a look at other PRs. Then I found they were rejected because of the same "Failed to add qdisc" and "Failed to remove qdisc" errors as well. Let me excerpt examples from last three PRs except for the one with the WIP tag:

- #256 ([Travis](https://travis-ci.org/vishvananda/netlink/builds/265028243?utm_source=github_status&utm_medium=notification))
- #257 ([Travis](https://travis-ci.org/vishvananda/netlink/builds/265242845?utm_source=github_status&utm_medium=notification))
- #259 ([Travis](https://travis-ci.org/vishvananda/netlink/builds/266700482?utm_source=github_status&utm_medium=notification))

@danwinship was also mentioning the flakiness of the CI in #257.

**Comment by danwinship** [comment]
FWIW I also get even more failures if I try to run the tests locally (Fedora 26, kernel 4.12.5). For some reason it was adding an object to netlink once but then getting back two copies of it so then the test would fail when checking that len() == 1. (I forget exactly where this was, and I don't want to run the tests again now because they also have the side effect of causing docker to break somehow; I gave up debugging at that point because I really don't know a lot about netlink anyway and wasn't sure if the results I was getting could be considered legit or not.)

**Comment by vishvananda** [comment]
yes there is an issue ever since travis switched to defaulting tests to run on trusty. I haven't had time to investigate yet

**Comment by vishvananda** [comment]
Ok ci is now fixed. I need to reenable more tests now that the kernel is newer but at least it is passing.

**Comment by tfukushima** [comment]
@vishvananda Thank you so much for taking your time on this!
