### ISSUE TITLE
Conntrack nat filters incompatibility

### ISSUE THREAD

**Issue by bboreham** [vishvananda/netlink#373]
I see in `github.com/vishvananda/netlink/conntrack_linux.go` the following comments, with code to match:

```
// Conntrack parameters and options:                                                                                                              
//   -n, --src-nat ip                      source NAT ip                                                                                          
//   -g, --dst-nat ip                      destination NAT ip                                                                                     
//   -j, --any-nat ip                      source or destination NAT ip                                                                           
```

This does not match the `conntrack` command, e.g. from its [man page](https://manpages.debian.org/testing/conntrack/conntrack.8.en.html)

```
-n, --src-nat
    Filter source NAT connections.
-g, --dst-nat
    Filter destination NAT connections.
-j, --any-nat
    Filter any NAT connections.
```

There is no IP address on these options - they simply filter the conntrack table for entries that involve NAT.

Of course, it's fine for `vishvananda/netlink` to document and implement something different from standard Linux conntrack.  But I did find it odd so thought I would raise this to check.

**Comment by vishvananda** [comment]
I believe that this is only an error in the comment and the functionality is the same as the conntrack command. Do you see an actual difference in the implementation?

**Comment by bboreham** [comment]
I'm looking at [this](https://github.com/vishvananda/netlink/blob/master/conntrack_linux.go#L374):

	match = match && elem.Equal(flow.Forward.DstIP)

where it is checking an IP, and there is no IP to check in the conntrack command.  So yes I think it is different.

**Comment by vishvananda** [comment]
hmm looks like you may be right. @fcrisciani I believe you authored that code. Any comments?

**Comment by fcrisciani** [comment]
@bboreham @vishvananda will have to check the code of the conntrack command, don't recall on top of my mind.
As far as I can see the filter aims to cover these:
```
      -s, --orig-src IP_ADDRESS
              Match only entries whose source address in the original direction equals the one specified as argument.

       -d, --orig-dst IP_ADDRESS
              Match only entries whose destination address in the original direction equals the one specified as argument.

       -r, --reply-src IP_ADDRESS
              Match only entries whose source address in the reply direction equals the one specified as argument.

       -q, --reply-dst IP_ADDRESS
              Match only entries whose destination address in the reply direction equals the one specified as argument.
```
That's why there is the match there.
The one that needs a review I guess is `ConntrackNatAnyIP         // -any-nat ip    Source or destination NAT ip` for which I don't remember the details, and what really the man means when says:
```
-j, --any-nat
              Filter any NAT connections.
```

**Comment by fcrisciani** [comment]
looked into more details and these flags are not implemented:
```
//   -n, --src-nat ip                      source NAT ip                                                                                          
//   -g, --dst-nat ip                      destination NAT ip                                                                                     
//   -j, --any-nat ip                      source or destination NAT ip
```
They are basically doing a filtering of flows that got natted with no specific IP match (that is still left in the hands of the other 4 flags before).
Right now it's more a documentation problem that can confuse people, and a lot of the options that I dumped there from the man are currently not implemented

Opened https://github.com/vishvananda/netlink/pull/374 to mitigate the issue. Unfortunately I cannot change the name of the constants because they may already be in use. I can duplicate the values with more appropriate naming maybe and eventually we can define a path to deprecate the current ones moving forward. @vishvananda @aboch suggestions about that?
