### ISSUE TITLE
Listing FDB entries against linux kernel 4.15 returns no results

### ISSUE THREAD

**Issue by adobley** [vishvananda/netlink#380]
We have discovered an potential regression on ubuntu-xenial when upgrading our environments from ubuntu-trusty. The change appears to manifest somewhere between 4.4.0 and 4.15.0 kernel versions.

When listing bridge fdb entries via this library, we do not receive any data.

We made a public gist with some minimal source code and instructions to reproduce.

https://gist.github.com/adobley/418ef631be957466a4514af7490455b7

Any help is greatly appreciated. Thanks!

**Comment by mfoliveira** [comment]
For documentation purposes.

This issue has been fixed in Linux v4.19-rc7 [1], and should soon be available in Ubuntu kernels.
Other distros should receive the fix normally via the stable kernel series/maintenance.

thanks!
[1] https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=bd961c9bc66497f0c63f4ba1d02900bb85078366

**Comment by adobley** [comment]
Closing for now, we'll reopen this if it is still a problem when we integrate the fix.

Thank you so much!
